#!/bin/bash
# Test Export Script
# This file is generated by EVM export command

# Application Settings
export APP_NAME="Shell Export App"
export APP_VERSION="3.0.0"
export APP_ENV="testing"

# Database Configuration
export DATABASE_URL="postgresql://test-db:5432/shelltest"
export DATABASE_USER="shelluser"
export DATABASE_PASSWORD="shellpass"

# API Configuration
export API_KEY="shell_api_key_xyz987"
export API_URL="https://shell-api.example.com"
export API_TIMEOUT="60000"

# Feature Flags
export DEBUG="false"
export ENABLE_CACHING="false"
export ENABLE_LOGGING="true"

# Security
export JWT_SECRET="shell_jwt_secret_token"
export ENCRYPTION_KEY="shell_encryption_key"

# Services
export EMAIL_ENABLED="true"
export SMS_ENABLED="true"
